import "./globals.css";
import { Geist , Nerko_One ,Comfortaa ,Cedarville_Cursive} from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });
const nerkoOne = Nerko_One({ subsets: ['latin'],  weight: ["400"], variable: '--font-nekro' });
const comfortaa = Comfortaa({ subsets: ['latin'],  weight: ["400"], variable: '--font-comfortaa' });
const cursive = Cedarville_Cursive({ subsets: ['latin'],  weight: ["400"], variable: '--font-cursive' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable, nerkoOne.variable, comfortaa.variable, cursive.variable)}>
      <body className="bg-[#272B30] text-white">
        {children}
      </body>
    </html>
  );
}
